version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: accountowner
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose: 
    - "3306"
    restart: always
  
  smashapi:
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://*:443;http://*:80
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/stembowl.pfx
    depends_on:
    - db
    image: smashapi
    build: ./
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https/
volumes:
    dbdata: