version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: accountowner
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: 
      - db-network    
    restart: always
  
  smashapi:
    environment:
      - ASPNETCORE_URLS=https://*:443;http://*:80
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/smashapi.pfx
      - APP_connectionString= server=db;port=3306;userid=dbuser;password=dbuserpassword;database=accountowner;
      - APP_JwtKey= "MIIJKQIBAAKCAgEAxr4r+ugvbuVWWJoIojfnhgbNZ8feeK2mnv7c/0eSyetSz2dI3rj0D+rcXFJTKtB9xOviqhzxIPOro5V4h4wLS3klGGk5uv511uibNejIzwfs6hFt0S2PzFugO4h0QO0/MdOBmVDEpTew5hJI7NpMiN/peODx4RaKn9yZscd6+tCNDNjIk2P33x6ct6Grl+IEqzor1O29p9HUXaJ5HLybFm5tlKBrogN68tpHpF5WZV6AOZc6TgJIdBtBIN7nlAGR+qQoi4cicuwC3A7JBRtrtK3orx5vQ8dA1NZm/iCKcXD14kCXjem32AcuZwWe4hIggQrCW1VdnopizjRXCs6PZ576ijriNFNDt6RYUuAvs+XueQi4Zx1n+WGVCxT8Mo7GB4LyUT0dCAa1nvhSh4pZEDxJaHfIpFuvRFWpX8opbcxZjUeWcudgqZKBpurZOXP6/dMLAD5NOgDbnc8jWX1+YCxtxZy40VYl6UTfFj0W3EcbqPc0rjGbnYDeCHx/mC65IWsrFFPJ2YCrrYkzOYbqE3tNQ9H2GtHOS2YBRJA5QNQrwpHO2caWIj5+/nSkBy7odQvUZUfcmFuxXfIlRcu6g6/6vlIf7t4XA4wowNzrsQC3HbcQB/eG93WBRxvgbXP0CDD3hEcY3rG3fco5nVMnlW1/haGXfjIETfUocKpBXh0CAwEAAQKCAgEAjpk+1y2ncwtMdBA5Z6NzFKBm2zL2dmIqbmRxzxzcvtKBPV1fVKciPxWF/Rv4nnyv8Q5LOUHA5aLQoXQK4j7ij8mhiy1dBcW0aXnGe9zF0H5gR+YvhGoLhlar1mtm9nsD381hbM8d+WnHHJ08A+3yAjeevmOwSY+x8VgIUx3NKI9g1TnqWI7e+BFv4vY2N6ktLmpzrrjSXspYdMKx4aOWJ3ceWwjrkXiry/pAczhZByzSFgBjDjvnHp+7kEk/oduqkUsd6FcSqaCbwKc/JtHw6tfpX1UYAmrCIrSfe3F/xDuHwUoVM/bhOTiV28eVo6Hb/prorz3GCY5DrK6zUYa6LxyLcGCPp92r1miYMX27b1s8y4JZ/j30+pzPumlady4ttB3OzPRrFGcCLrE/uRWoCm7vSU1zWAabwgLYFoaNd+Gb7QcNPOBc+pWJJxUUZ8lgEh++F985qDYld712Ht3SDGW4jxvAZrjMVx/ipXU4soLgNqapAdDx7iuKscgupgFLKntqPiOi99RAjCl+fJVX3gFfwynaZpydQHLh9sykSnT29cSF+cVUMDcsldbzgStc1Jp28Sj7L9b4LOYjH+NWhlZDoOhr9qbIADyCVqvdBlXvAR3sA7lcdoX7SqboWP33RQrwd273FSQfS9vGyJNAE3UQie+g8Xk3amEMwy9VICECggEBAOYQV/hii46KSY5G5QAghLuF6vE8J0dOag/3cGDkahoeD5nixWNWhKFOYiubvbZPyZ1H78ErVbC7I1BJqGYMStqWbGf97djuLm1pwNKLOa9WfkNWXSkgc9PanKa7IwZE79lBWQdZkckJXNTNYGEJi91ieb+h6R8BYim9nlN92TysVffamWLyCd0B1kUCmkwQpZ1bsfe2eQ3sE0NlZqugdwXZEBxe51SLUd9ikNUNrPDfc5/IC116y9Hp4/Wvf2J7uDeULRUY";
      - APP_JwtIssuer= http://localhost:443;
    depends_on:
    - db
    image: smashapi
    build: ./
    ports:
    - "5500:80"
    - "5501:443"
    volumes:
      - /home/cslaf/.aspnet/https:/root/.aspnet/https/
    networks: 
      - db-network

volumes:
    dbdata:

networks:
  db-network:
